language: python
python:
  - "2.7"

os:
  - linux
  - osx

env:
  global:
    - RMGPY_REPO='https://github.com/ReactionMechanismGenerator/RMG-Py.git'
    - RMGDB_REPO='https://github.com/ReactionMechanismGenerator/RMG-database.git'
    - RMGPY_TAG='stable'
    - RMGDB_TAG='stable'

before_install:
  - cd ..
  # Install miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a
  # Clone RMG-Py
  - git clone $RMGPY_REPO
  - cd RMG-Py
  - git checkout $RMGPY_TAG
  - cd ../
  # Clone RMG-database
  - git clone $RMGDB_REPO
  - cd RMG-database
  - git checkout $RMGDB_TAG
  - cd ../

install:
  - cd RMG-Py
  - conda env create -q -f environment_linux.yml
  - source activate rmg_env
  - conda list
  - yes 'Yes' | $HOME/miniconda/envs/rmg_env/bin/mopac $MOPACKEY > /dev/null
  - make

script:
  - make test-unittests
  - make test-functional
  - make test-database

after_success:
  - make clean
  - source deactivate
  - cd ../
  - conda install -y conda-build
  - conda config --add channels rmg
  - conda build RMG-database
  - conda build RMG-Py

